spring:
  datasource:
    url: jdbc:mysql://localhost/PlanIT?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1543

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

fileStorage:
  dir: /Users/gimmunjin/planit/back-end


# 환경변수 설정
# - DB USER_NAME, PASSWORD
# - 파일 저장 디렉토리 경로
