spring:
  profiles:
    active:
      on-profile: prod # 기본 환경을 prod로

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB

  fileStorage:
    dir: ${FILE_STORAGE_DIR}

  jwt:
    secret-key: ${SECRET_KEY}
    access-token-expire: ${ACCESS_EXPIRE}
    refresh-token-expire: ${REFRESH_EXPIRE}

  datasource:
    url: jdbc:mysql://${DB_CONNECTION_URL}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mvc:
    cors:
      allowed-origins: "*"

  logging:
    pattern:
      console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
      file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
    logback:
      rollingpolicy:
        file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
    file:
      name: logs
      max-history: 7
      max-size: 5KB
      total-size-cap: 1MB
    level:
      org:
        springframework: DEBUG

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    login-uri: https://nid.naver.com/oauth2.0/authorize?response_type=code&
    redirect-uri: http://localhost:3000/login/oauth2/code/naver

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    login-uri: https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?
    redirect-uri: http://localhost:3000/login/oauth2/code/google

  email:
    app-key: ${EMAIL_APP_KEY}
    redis-timeLimit: 300000